### PR TITLE
Implement public mentor page

### LINKED ISSUE #9: Implement the mentors public page
### Description
As part of this issue, we need to create the "mentors" public page, which should closely match the provided mockup. This will provide the users with a way to see all the mentors registered on the platform.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the mentors public page, following the provided mockup.
1. Make sure that both the List view and the Card view is availble and the user can easily switch between them.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

### Card View
Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=2504-4902&mode=design&t=OFxJkHITzop09S2b-4

image

Note: You may want to mock the API refer to the [API doc](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#1127356a-3542-4ceb-9477-9d68cf863d5a) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written

### PR DESCRIPTION
**Pull request by Madhawa97**
## Purpose

The purpose of this PR is to fix #9 

## Goals

The goal of this PR is to implement public mentor page

## Screenshots

Screenshot 2024-04-07 at 11 46 51

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Madhawa97** [comment]
Do we remove unused fields from profile? like the `first_name`, `last_name` and etc.
```json
        {
            "state": "approved",
            "category": {
                "category": "Computer Science",
                "uuid": "406397fc-3cff-4780-a361-7db345845bb6",
                "created_at": "2024-01-03T16:08:12.214Z",
                "updated_at": "2024-01-03T16:08:12.214Z"
            },
            "application": {
                "firstName": "John",
                "lastName": "Doe",
                "email": "madhawa97@gmail.com",
                "contactNo": "+94779970622",
                "country": "Sri Lanka",
                "position": "SE at Google Inc",
                "expertise": "Fullstack engineering",
                "bio": "Yadi yada",
                "isPastMentor": true,
                "reasonToMentor": "Makes me happy",
                "motivation": "Boom",
                "cv": "https://www.linkedin.com/in/madhawamonara/",
                "menteeExpectations": "Enthusiastic",
                "mentoringPhilosophy": "Yadi yada",
                "noOfMentees": 5,
                "canCommit": true,
                "mentoredYear": 2020,
                "category": "406397fc-3cff-4780-a361-7db345845bb6",
                "institution": "ITUM",
                "linkedin": "https://www.linkedin.com/in/madhawamonara/",
                "website": "https://www.linkedin.com/in/madhawamonara/"
            },
            "availability": true,
            "profile": {
                "primary_email": "madhawa97@gmail.com",
                "contact_email": "",
                "first_name": "",
                "last_name": "",
                "image_url": "",
                "linkedin_url": "",
                "type": "default",
                "uuid": "1f766bf2-045a-4a27-8087-8c6b8e2b4561",
                "created_at": "2024-03-24T11:49:50.390Z",
                "updated_at": "2024-03-24T11:49:50.390Z"
            },
            "uuid": "86b65e78-dde4-447a-9abb-c72a4b86cf6f",
            "created_at": "2024-03-24T11:54:49.599Z",
            "updated_at": "2024-03-24T11:54:49.599Z"
        },
```

**Comment by anjula-sack** [comment]
> Do we remove unused fields from profile? like the `first_name`, `last_name` and etc.
> 
> ```json
>         {
>             "state": "approved",
>             "category": {
>                 "category": "Computer Science",
>                 "uuid": "406397fc-3cff-4780-a361-7db345845bb6",
>                 "created_at": "2024-01-03T16:08:12.214Z",
>                 "updated_at": "2024-01-03T16:08:12.214Z"
>             },
>             "application": {
>                 "firstName": "John",
>                 "lastName": "Doe",
>                 "email": "madhawa97@gmail.com",
>                 "contactNo": "+94779970622",
>                 "country": "Sri Lanka",
>                 "position": "SE at Google Inc",
>                 "expertise": "Fullstack engineering",
>                 "bio": "Yadi yada",
>                 "isPastMentor": true,
>                 "reasonToMentor": "Makes me happy",
>                 "motivation": "Boom",
>                 "cv": "https://www.linkedin.com/in/madhawamonara/",
>                 "menteeExpectations": "Enthusiastic",
>                 "mentoringPhilosophy": "Yadi yada",
>                 "noOfMentees": 5,
>                 "canCommit": true,
>                 "mentoredYear": 2020,
>                 "category": "406397fc-3cff-4780-a361-7db345845bb6",
>                 "institution": "ITUM",
>                 "linkedin": "https://www.linkedin.com/in/madhawamonara/",
>                 "website": "https://www.linkedin.com/in/madhawamonara/"
>             },
>             "availability": true,
>             "profile": {
>                 "primary_email": "madhawa97@gmail.com",
>                 "contact_email": "",
>                 "first_name": "",
>                 "last_name": "",
>                 "image_url": "",
>                 "linkedin_url": "",
>                 "type": "default",
>                 "uuid": "1f766bf2-045a-4a27-8087-8c6b8e2b4561",
>                 "created_at": "2024-03-24T11:49:50.390Z",
>                 "updated_at": "2024-03-24T11:49:50.390Z"
>             },
>             "uuid": "86b65e78-dde4-447a-9abb-c72a4b86cf6f",
>             "created_at": "2024-03-24T11:54:49.599Z",
>             "updated_at": "2024-03-24T11:54:49.599Z"
>         },
> ```

Applications shouldn't be retrieved

**Comment by Madhawa97** [comment]
@anjula-sack I have updated the MentorCardType to match with the backend response and also added a new mentorCards mock to support the stories. 
But if we send the fields mentorId as uuid and category as Category type, then we could use the mentors mock as well. 

Also seems like we don't keep track of the mentor's company or institution. Is it intentional?

**Review by anjula-sack — APPROVED** [review]
Good job! @Madhawa97

**Pull request merged**
