### PR TITLE
Home page tailwindcss development

### LINKED ISSUE #50: Migrate from ant design to tailwind css
**Is your feature request related to a problem? Please describe.**
- Since we decided to use tailwind CSS we need to change the existing components from ant design to tailwind css

**Describe the solution you'd like**
- Create the existing components in tailwind css
- Remove ant design from the project

### PR DESCRIPTION
**Pull request by MethmaPeiris99**
## Purpose

The purpose of this PR is to fix #50 

## Goals

- The UI was developed referring the [Home Page mockup](https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=807-925&mode=design&t=DDmHwSzuKp3IxOxz-0)
- TailwindCSS was utilized to style the fonts and buttons in the home page
- Flex and Grid attributes in TailwindCSS are used to align the elements in the home page

## Approach

The UI of the home page of ScholarX version 2 was migrated to TailwindCSS by removing the Ant Design components. Refer [TailwindCSS documentation](https://tailwindcss.com/) for more information.

### Navbar and Hero Section
image

### Statistics and Testimonial Section
image

### Success Stories and Archive Section
image

### FAQ for Mentors and Mentees Section
image

### Footer Section
image

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by anjula-sack — CHANGES_REQUESTED** [review]
Remove ant design from the package json and run npm install.

**Review by anjula-sack — CHANGES_REQUESTED** [review]
Update the mentor card and other components as well

**Comment by MethmaPeiris99** [comment]
> Remove ant design from the package json and run npm install.

Done !

**Review by anjula-sack — CHANGES_REQUESTED** [review]
The build is failing can you check @MethmaPeiris99?

**Pull request closed without merging**
